name: 'Release Image'
description: 'Release Docker image on ghcr.io'
inputs:
  image:
    description: 'short image name without repo/owner and tag, e.g. platformstorageapi'
    required: true
  artifact:
    description: 'The artifact name uploaded by workflow_run workflow'
    required: false
    default: 'image'
  token:
    description: 'github token, <secrets.GITHUB_TOKEN>'
    required: true
outputs:
  version:
    description: "Version"
    value: ${{ steps.run.outputs.version }}
  skip:
    description: "Skip"
    value: ${{ steps.run.outputs.skip }}
  tag:
    description: "Tag"
    value: ${{ steps.run.outputs.tag }}
  prerelease:
    description: "Prerelease"
    value: ${{ steps.run.outputs.prerelease }}
runs:
  using: "composite"
  steps:
    - name: Collect meta info
      id: run
      run: ${{ github.action_path }}/main.py
      shell: bash
      env:
          INPUT_GITHUB: ${{ toJson(github) }}
          INPUT_IMAGE:  ${{ inputs.image }}
          INPUT_ARTIFACT:  ${{ inputs.artifact }}
          INPUT_TOKEN:  ${{ inputs.token }}
